#!/bin/bash

echo "╔═══════════════════════════════════════════════════════╗"
echo "║       店小蜜认证服务器 - 一键部署指南                ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}步骤 1: 准备工作${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ 已创建部署配置文件:"
echo "  - Dockerfile (Docker部署)"
echo "  - railway.json (Railway部署)"
echo "  - render.yaml (Render部署)"
echo "  - .env.example (环境变量模板)"
echo ""
echo "✓ 已创建管理工具:"
echo "  - npm run create-customer (创建客户账号)"
echo "  - npm run list-accounts (查看所有账号)"
echo ""

echo -e "${BLUE}步骤 2: 推送代码到 GitHub${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "运行以下命令:"
echo ""
echo -e "${YELLOW}cd /Users/bilibili/dxm/dianxiaomi-auth-server${NC}"
echo -e "${YELLOW}git add .${NC}"
echo -e "${YELLOW}git commit -m \"Add deployment configurations\"${NC}"
echo -e "${YELLOW}git push${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo -e "${BLUE}步骤 3: 创建 MongoDB Atlas 数据库（免费）${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问: https://www.mongodb.com/cloud/atlas"
echo "2. 注册/登录账号"
echo "3. 创建免费集群 (M0 Free Tier)"
echo "4. 选择云服务商和地区 (推荐: AWS - 香港/新加坡)"
echo "5. 网络访问: 允许所有IP (0.0.0.0/0)"
echo "6. 创建数据库用户: 用户名 + 密码"
echo "7. 获取连接字符串，格式如下:"
echo ""
echo -e "${YELLOW}mongodb+srv://用户名:密码@cluster0.xxxxx.mongodb.net/dianxiaomi_auth${NC}"
echo ""
echo "复制这个连接字符串，稍后需要使用"
echo ""
read -p "按回车键继续..."

echo ""
echo -e "${BLUE}步骤 4: 在 Railway 部署服务器（推荐）${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问: https://railway.app/"
echo "2. 使用 GitHub 登录"
echo "3. 点击 'New Project' -> 'Deploy from GitHub repo'"
echo "4. 选择 'dianxiaomi-auth-server' 仓库"
echo "5. 等待自动部署完成"
echo ""
echo "6. 配置环境变量（Settings -> Variables）:"
echo -e "${YELLOW}   NODE_ENV=production${NC}"
echo -e "${YELLOW}   PORT=3000${NC}"
echo -e "${YELLOW}   MONGODB_URI=<你的MongoDB Atlas连接字符串>${NC}"
echo -e "${YELLOW}   JWT_SECRET=<生成的随机密钥>${NC}"
echo -e "${YELLOW}   ALLOWED_ORIGINS=chrome-extension://*${NC}"
echo ""
echo "生成 JWT_SECRET 命令:"
echo -e "${YELLOW}node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"${NC}"
echo ""
echo "7. 重新部署（Deploy -> Redeploy）"
echo "8. 获取部署地址，例如: https://xxx.up.railway.app"
echo ""
read -p "按回车键继续..."

echo ""
echo -e "${BLUE}步骤 5: 更新 Chrome 插件配置${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "编辑文件: /Users/bilibili/dxm/dianxiaomi/utils/auth-config.js"
echo ""
echo "找到这一行:"
echo -e "${YELLOW}API_BASE_URL: 'http://localhost:3000/api',${NC}"
echo ""
echo "改为你的 Railway 地址:"
echo -e "${GREEN}API_BASE_URL: 'https://你的Railway地址.up.railway.app/api',${NC}"
echo ""
echo "然后在 Chrome 扩展页面刷新插件"
echo ""
read -p "按回车键继续..."

echo ""
echo -e "${BLUE}步骤 6: 创建客户账号${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "在本地运行（需要配置 .env 连接到 MongoDB Atlas）:"
echo ""
echo -e "${YELLOW}npm run create-customer${NC}"
echo ""
echo "或者通过 Railway 的 Shell 运行"
echo ""
echo "订阅计划："
echo "  • 免费版 (free)     - ¥0    - 3设备  - 30天"
echo "  • 基础版 (basic)    - ¥199  - 5设备  - 1年"
echo "  • 高级版 (premium)  - ¥499  - 10设备 - 1年"
echo "  • 企业版 (enterprise) - ¥1999 - 50设备 - 1年"
echo ""
read -p "按回车键继续..."

echo ""
echo -e "${BLUE}步骤 7: 测试完整流程${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 打开 Chrome 插件"
echo "2. 使用创建的账号登录"
echo "3. 检查设备注册是否成功"
echo "4. 测试各项功能"
echo ""

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              部署准备完成！                           ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""
echo "📚 详细文档: DEPLOYMENT.md"
echo ""
echo "常用命令:"
echo "  • 创建客户: npm run create-customer"
echo "  • 查看账号: npm run list-accounts"
echo "  • 启动服务: npm start"
echo ""
echo "现在可以开始售卖了！🎉"
echo ""
